---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  labels:
    app: hello-kubernetes
    test: label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
      test: label
  template:
    metadata:
      labels:
        app: hello-kubernetes
        test: label
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-kubernetes
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hello-kubernetes
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`<your-domain>`)
    kind: Rule
    services:
    - name: hello-kubernetes
      port: 80
